"""tournament table

Revision ID: 224247aa0e7d
Revises: 097b3a9855eb
Create Date: 2020-02-04 16:31:21.256782

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '224247aa0e7d'
down_revision = '097b3a9855eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tournament',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tournament_name', sa.String(length=64), nullable=True),
    sa.Column('organizer_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['organizer_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bracket',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bracket_type', sa.String(length=20), nullable=True),
    sa.Column('tournament_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournament.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bracket_entrants',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('bracket_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bracket_id'], ['bracket.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'bracket_id')
    )
    op.create_table('round',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.Column('winners', sa.Boolean(), nullable=True),
    sa.Column('bracket_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bracket_id'], ['bracket.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('match',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_1', sa.Integer(), nullable=True),
    sa.Column('user_2', sa.Integer(), nullable=True),
    sa.Column('round_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['round_id'], ['round.id'], ),
    sa.ForeignKeyConstraint(['user_1'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_2'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('match')
    op.drop_table('round')
    op.drop_table('bracket_entrants')
    op.drop_table('bracket')
    op.drop_table('tournament')
    # ### end Alembic commands ###
