"""added n_entrants to Tournament model

Revision ID: 5c0f41322ca4
Revises: 224247aa0e7d
Create Date: 2020-02-05 07:14:55.772521

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c0f41322ca4'
down_revision = '224247aa0e7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tournament', sa.Column('n_entrants', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tournament', 'n_entrants')
    # ### end Alembic commands ###
