"""update match id user attribute

Revision ID: 732c78f50762
Revises: 49499b533153
Create Date: 2020-02-08 17:07:07.301657

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '732c78f50762'
down_revision = '49499b533153'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # meta = MetaData

    with op.batch_alter_table('user') as batch_op:

        batch_op.alter_column('match_id',
                existing_type=sa.INTEGER(),
                nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'match_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
