"""renamed name field in Tournament

Revision ID: 81a88e019a16
Revises: 5c0f41322ca4
Create Date: 2020-02-05 07:54:42.592878

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81a88e019a16'
down_revision = '5c0f41322ca4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_column('tournament', 'tournament_name')
    with op.batch_alter_table('tournament') as batch_op:
        batch_op.drop_column('tournament_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tournament', sa.Column('tournament_name', sa.VARCHAR(length=64), nullable=True))
    # ### end Alembic commands ###
